### ISSUE TITLE
Update README.md file 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#102]
## TO-DOs

- [x] Add information about Hubspot
- [x] Emails that are attached to crm
- [ ] add info about issue templates
- [x] Addi information about Ticket center

Use formating from [#16](https://github.com/compilerla/compiler.la/issues/16) to add details to README.md

**Comment by AnthonyRollins** [comment]
Draft of content needed for readme.md file.

Getting Started |   |   |  
-- | -- | -- | ---
**Section** | **Description** |   |  
Database | Contacts, Companies |   |  
Conversations | CRM@ and Hello@ emails populate the Conversations inbox. |   |  
Service | Ticketing |   |  
CRM@ | Adding this email adds emails to Conversations inbox and add all activity to each contact and company profile |   |  
Hello@ |   |   |  
  |   |   |  
**Key Terms** |   |   |  
**Keyword** | **Definition** |   |  
Hubspot Objects |   |   
Object ID |   |   
Contacts |   |   
Companies |   |   
Conversations |   |   
Sales |   |   
--Deals |   |   
--Pipelines |   |   
Services |   |   
--Tickets |   |

**Comment by AnthonyRollins** [comment]
updated content to the README.md file
