### ISSUE TITLE
Add new GTFS pipeline 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#103]
## To-Dos 
- [ ] Create new pipeline called `GTFS Compliance`
- [ ] Add the following stages `Assessment Pending` `Planned: In Development` `Planned: Complete` `In Progress` `Complete`
- [ ] Make a copy of [Data Assessment Outreach import spreadsheet](https://docs.google.com/spreadsheets/d/1995hIaMXxSqbQTPwKt2jr2w4ry8AJzK7AGeZGntpbVg/edit#gid=0) for importing into new pipeline.

**Comment by AnthonyRollins** [comment]
New Deals pipeline: [GTFS Compliance](https://app.hubspot.com/contacts/5519226/objects/0-3/views/all/board?redirectFrom=crm-records-ui
) 
New import [sheet](https://docs.google.com/spreadsheets/d/1ZDYokg19keYsrQO8Y3Fs83-K78p9ZE-Hj3GejfU---k/edit#gid=0) for GTFS Compliance pipeline.
