### ISSUE TITLE
Add dot.ca.gov email/calendar with Hubspot

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#127]
## To-Do

- [ ] Discuss with Evan / Hunter the best route to get this approved
- [ ] Open a SNOW ticket with Caltrans IT
- [ ] Test adding `dot.ca.gov` emails to Hubspot
- [ ] Announce to all of Cal-ITP, so users can start adding their `dot.ca.gov` emails.

![3d9620eb-007e-46bb-8394-5e363ba6638a_large](https://user-images.githubusercontent.com/25047205/186746020-fa2ef3e3-857b-4931-a758-edb9a8656a9c.png)

**Comment by AnthonyRollins** [comment]
@evansiroky Any update on getting the SNOW ticket approved?

**Comment by AnthonyRollins** [comment]
@hunterowens, I read through the Slack [thread](https://cal-itp.slack.com/archives/C015B2EBHU0/p1658872879724779) - any update on this ticket with SNOW?

**Comment by vykster** [comment]
Old snow ticket number: RITM0171936

@hunterowens @evansiroky I forgot about the status of the snow ticket for getting the dot emails set up in the CRM, is there an open snow ticket for this? I feel like we came up with a plan and I forgot what it was.

**Comment by vykster** [comment]
@thekaveman do you remember the name of the person who helped with setting up the forwards for dot emails when we were configuring stuff in teamwork way back?

**Comment by vykster** [comment]
New snow ticket number: RITM0140360, [draft ticket in google doc](https://docs.google.com/document/d/1N-urcZzNPEgLHw9MZ2IDOanG62vEXDNKpaKT3manHco/edit)

**Comment by thekaveman** [comment]
Based on [the Slack thread](https://cal-itp.slack.com/archives/C01CT346NDC/p1675276072018539?thread_ts=1675275560.439859&cid=C01CT346NDC), I think RITM0140360 was the original ticket Evan submitted to get gtfsrt@dot forwarded, related to getting calitp@dot forwarded (Issue #210). 

That is not the RITM for getting DOT emails added to HubSpot (what this issue tracks), that Hunter submitted on 1/18/23.
