### ISSUE TITLE
[Property Request]: Edit GTFS features and add a few more

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/crm-helpdesk#144]
### What is the problem that this is solving?

# Overview
The purpose of adding the GTFS and GTFS-rt features as properties in CRM was to allow for Cal-ITP staff to accurately represent where agencies currently are based on the Transit Data Guidelines v3. However, because the authoritative list of features has changed since they were initially added to CRM, we need to update the properties in CRM to bring them into consistency with the TDG.

# Requirements
* Change `GTFS Schedule: On the Map` to `GTFS Schedule: Compliance`
* Eliminate `GTFS Schedule: Complete`
* Change `GTFS Schedule: FR Complete` to `GTFS Schedule: FR Completeness`
* Change `GTFS Schedule: DR Complete` to `GTFS Schedule: DR Completeness`
* Change `GTFS Schedule: ADA Accessible` to `GTFS Schedule: Accurate Accessibility Data`
* Change `GTFS Schedule: Accurate` to `GTFS Schedule: Service Accuracy`
* Change `GTFS Schedule: Up to Date` to `GTFS Schedule: Up-to-Dateness`
* Change `GTFS Schedule: DR Complete` to `GTFS Schedule: DR Completeness`
* Change `GTFS Schedule: Fares` to `GTFS Schedule: Fare Completeness`
* Change `GTFS Schedule: Best Practices` to `GTFS Schedule: Best Practices Alignment`
* Change `GTFS rt: On the Map` to `GTFS rt: Compliance`
* Eliminate `GTFS rt: Complete`
* Change `GTFS rt: FR Complete` to `GTFS rt: FR Completeness`
* Change `GTFS rt: DR Complete` to `GTFS rt: DR Completeness`
* Change `GTFS rt: Accurate` to `GTFS rt: Service Accuracy`
* Change `GTFS rt: Best Practices` to `GTFS rt: Best Practices Alignment`
* Create new properties
** `Data Availability: Feed Aggregator Availability`
** `Data Availability: Technical Contact`
** `Data Availability: Website Availability`
** All the new properties should be dropdowns with the same selectable options as before

**Comment by AnthonyRollins** [comment]
## To-Do
- [ ] Change GTFS Schedule: On the Map to GTFS Schedule: Compliance
- [ ] Eliminate GTFS Schedule: Complete
- [ ] Change GTFS Schedule: FR Complete to GTFS Schedule: FR Completeness
- [ ] Change GTFS Schedule: DR Complete to GTFS Schedule: DR Completeness
- [ ] Change GTFS Schedule: ADA Accessible to GTFS Schedule: Accurate Accessibility Data
- [ ] Change GTFS Schedule: Accurate to GTFS Schedule: Service Accuracy
- [ ] Change GTFS Schedule: Up to Date to GTFS Schedule: Up-to-Dateness
- [ ] Change GTFS Schedule: DR Complete to GTFS Schedule: DR Completeness
- [ ] Change GTFS Schedule: Fares to GTFS Schedule: Fare Completeness
- [ ] Change GTFS Schedule: Best Practices to GTFS Schedule: Best Practices Alignment
- [ ] Change GTFS rt: On the Map to GTFS rt: Compliance
- [ ] Eliminate GTFS rt: Complete
- [ ] Change GTFS rt: FR Complete to GTFS rt: FR Completeness
- [ ] Change GTFS rt: DR Complete to GTFS rt: DR Completeness
- [ ] Change GTFS rt: Accurate to GTFS rt: Service Accuracy
- [ ] Change GTFS rt: Best Practices to GTFS rt: Best Practices Alignment

**Comment by AnthonyRollins** [comment]
@safrazier17 Updated all the properties above and added in the new ones. Did the new properties need the same list of statuses as the other properties:

- Assessment Pending
- Not Applicable
- Unwanted
- Needed
- Planned
- Ready
- In-Progress
- Blocked
- Complete
- Issue Raised

**Comment by safrazier17** [comment]
They do need the same statuses yeah. Thanks Anthony

**Comment by AnthonyRollins** [comment]
@safrazier17 All properties have been updated and or added. Let me know if you have any changes.
