### ISSUE TITLE
Upgrade Hubspot: Transactional Emails

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#189]
## To-Dos
- [x] Budget approval for 2023
- [x] Reach out to Hubspot Customer Service to add-on transaction emails
- [ ] Create a Private App API key and send to GH Issue: https://github.com/cal-itp/reports/issues/209

**Comment by AnthonyRollins** [comment]
@thekaveman I created this ticket for transactional emails, so I will add the next steps here.

## To-Dos
- [ ] Connect and verify hello@calitp.org (Olivia confirmed this) as the [dedicated IP address](https://app.hubspot.com/settings/5519226/domains)
- [ ] Create a [transactional email private app ](https://app.hubspot.com/private-apps/5519226) in Hubspot

**Comment by thekaveman** [comment]
Both _Email sending domain_ and _Dedicated IP_ are all configured in Hubspot:

![image](https://user-images.githubusercontent.com/1783439/218862549-50419475-9d42-47f6-ba4d-e3f91bf2f92b.png)

**Comment by thekaveman** [comment]
I verified that Transactional Emails work from within Hubspot (not using the API): https://app.hubspot.com/email/5519226/details/102510193323

**Comment by thekaveman** [comment]
Ticket successfully created by replying to the test Transactional Email: https://app.hubspot.com/contacts/5519226/ticket/1437707697

**Comment by AnthonyRollins** [comment]
@thekaveman I looked through Hubspot's documentation on [transactional emails](https://knowledge.hubspot.com/email/how-to-use-transactional-email-in-hubspot), but I need help finding information on `email-id` besides when sending as a single-send API. Does the subscription type only need to read `transactional,` or is there something else I am missing to get that `email-id`. I am happy to book some time for this with you, but there may be an easy direction here.

**Comment by thekaveman** [comment]
@AnthonyRollins I think the Reports team will be using the single-send API, so I think these steps are accurate:

> If you plan to send the transactional email using the single-send API:
> * Click the Actions dropdown menu in the upper right and select Convert to single send API.
> * After you finish creating your email, you can copy the email ID when using the single send API. Learn more about sending a transactional email using the single send API in [HubSpot's developer documentation](https://developers.hubspot.com/docs/api/marketing/transactional-emails).

**Comment by thekaveman** [comment]
Closing this. The upgrade is complete on the CRM side and switch-over in email sending in-progress on the Reports website side.
