### ISSUE TITLE
[Feature Request]: Send press outreach from Hubspot

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#191]
### Feature Request

Using an existing Constant Contact list of press contacts, we would like to start sending press releases out from Hubspot's marketing email newsletter feature.

## To-do
- [ ] Retrieve data from Erika
- [ ] Upload data into Hubspot (tag as press contacts)
- [ ] Build a newsletter using an existing template 

### Is this request related to a problem?

We want all information to be tied to the CRM

### Use Case

Send out press release to our press contact list.

### Additional Info

n/a

**Comment by AnthonyRollins** [comment]
@esquared415 Would you be able to send over the press list you use?

**Comment by esquared415** [comment]
Sorry, @AnthonyRollins, I missed this tag. 

Did you already pull the one from Constant Contact? (That's what I use.) And Vyki's list on Google Drive?

If you'd like either of those, let me know and I'll send them over ... just let me know where to send.

**Comment by AnthonyRollins** [comment]
Feel free to send them over in Slack, I don't have access to Constant Contact, but I do have access to Vyki's list - thanks!

**Comment by esquared415** [comment]
@AnthonyRollins Downloaded and Slacked to you!

**Comment by AnthonyRollins** [comment]
@esquared415 Thanks! I've added all of them to Hubspot.
