### ISSUE TITLE
Develop website forms in Hubspot

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#193]
## To-Do
- [x] Draft [Hubspot form fields](https://docs.google.com/spreadsheets/d/1i28DPKdgzPncmD6fLz4LvHVHZC-q2TFQirzF-VkKVIM/edit#gid=0) using propose question types
- [x] Upgrade Hubspot to CRM Suite Professional
- [x] Meet with Kegan to review Raw HTML embed code.
- [x] Connect with Marissa on the final form
- [x] Draft form and send embed code to Marissa and Dev team

**Comment by AnthonyRollins** [comment]
@o-ram Can you take a look at the Hubspot forms I created for the website and make sure we have the right ticket properties? 
- [Transit Agency Form](https://app.hubspot.com/forms/5519226/editor/467e7cdc-0b55-4f0d-b36f-3f6b1f3d19ab/edit/form)
- [Vendor Form](https://app.hubspot.com/forms/5519226/editor/de22d690-184f-404d-b787-6f33e993b399/edit/form)
- [Other Form](https://app.hubspot.com/forms/5519226/editor/10ed070e-42c4-4451-b547-a6268123cc80/edit/form)

**Comment by thekaveman** [comment]
This is being tracked in the MobiMart repo under cal-itp/mobility-marketplace#424

**Comment by o-ram** [comment]
@AnthonyRollins The ticket properties look good to me! A couple of other bits of feedback though:

- In the [other form](https://app.hubspot.com/forms/5519226/editor/10ed070e-42c4-4451-b547-a6268123cc80/edit/form), first name and last should be required fields
- In all forms, the capitalization for the fields should match the [spreadsheet](https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit#gid=2006638120) so some of the form labels will need to be updated (mainly the ones like First Name, Phone Number, where the "n" is currently lowercase)

**Comment by AnthonyRollins** [comment]
Thanks for looking those over. I believe I made all the necessary corrections to those forms. Let me know if there should be any other changes.

**Comment by o-ram** [comment]
They all look good to go. Thanks!

**Comment by AnthonyRollins** [comment]
Sent forms via https://github.com/cal-itp/mobility-marketplace/issues/424
