### ISSUE TITLE
Draft OKR document 

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/crm-helpdesk#207]
## To-Do
- [x] Transfer OKR info from Miro to the Cal-ITP template
- [x] Send to @ProvvidenzaC @AnthonyRollins and @o-ram for internal review
- [x] Send to Marissa for final review
